pipeline{
    agent{
        label "maven"
    }
    options { skipdefaultCheckout true }
    stages{
        stage("Checkout"){
            steps{
                git branch: 'notifications', url: 'https://github.com/ran000/DO400-apps
            }
        }

        stage("Test"){
            steps{
                dir('simple-calculator') {
                    sh "./mvnw clean test"
                }
            }
        }
    }
}
