pipeline{
    agent{
        label "maven"
    }
    options { skipDefaultCheckout true }
    stages{
        stage("Checkout"){
            steps{
                sendNotification('started', 'team@example.com')
                git branch: 'notifications', url: 'https://github.com/ran000/DO400-apps'
            }
        }

        stage("Test"){
            steps{
                dir('simple-calculator') {
                    sh "./mvnw clean test"
                }
            }
        }
    }
}
void sendNotification(String action, String email) {
    mail to: "${emal}",
        subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}

