pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    environment {
            APP_NAMESPACE = "developer-security-scans"
        }
    stages {
        stage('Tests') {
            steps {
                dir('shopping-cart') { 
                    sh './mvnw clean test'
                }
            }
        }
        stage('Image Build') {
            steps {
                dir('shopping-cart') { 
                    sh '''
                        oc start-build security-scans --follow --wait -n ${APP_NAMESPACE}
                    '''
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('shopping-cart') { 
                    sh '''
                        oc rollout restart deployment/security-scans -n ${APP_NAMESPACE}
                    '''
                }
            }
        }

    }
}
