pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    environment {
            APP_NAMESPACE = "developer-security-scans"
        }
    stages {
        stage('Tests') {
            steps {
                dir('shopping-cart') { 
                    sh './mvnw clean test'
                }
            }
        }
        stage('Image Build') {
            steps {
                dir('shopping-cart') { 
                    sh '''
                        oc start-build security-scans --follow --wait -n ${APP_NAMESPACE}
                    '''
                }
            }
        }
        stage('Security Scan') {
            steps {
                dir('shopping-cart') { 
                    sh '''
                        oc process -f kubefiles/security-scan-template.yml -p PROJECT_NAME=${APP_NAMESPACE} -n ${APP_NAMESPACE} | oc replace -n ${APP_NAMESPACE} --force -f -
                    '''
                    sh "../tools/check-job-state.sh security-scans-trivy ${APP_NAMESPACE}"
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('shopping-cart') { 
                    sh '''
                        oc rollout restart deployment/security-scans -n ${APP_NAMESPACE}
                    '''
                }
            }
        }
    }
}
