pipeline {
    agent {
        label 'nodejs'
    }
    stages {
        stage('Install dependencies') {
            steps {
                dir ('exchange-cli') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir ('exchange-cli') {
                    sh 'npm run build'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir ('exchange-cli') {
                    sh 'npm run test:unit'
                }
            }
        }
        stage('Unit Functional') {
            steps {
                dir ('exchange-cli') {
                    sh 'npm run test:functional'
                }
            }
        }
    }
}

